val1 = int(input("\nEntre com o dividendo: "))
val2 = int(input("\nEntre com o divisor: "))
quoc = (val1 / val2)
rest = (val1 % val2)
print("\n\n\n")
print("\nDividendo:", val1)
print("\nDivisor:", val2)
print("\nQuociente:", quoc)
print("\nResto:", rest)
print("\n")