nome = str(input("\nDigite o nome: "))
print("\nNome:", nome)
print("\nPrimeiro caractere:", nome[0])
print("\nÚltimo caractere:", nome[-1])
print("\nPrimeiro ao terceiro caractere:", nome[:3])
print("\nQuarto caractere:", nome[3])
print("\nTodos menos o primeiro caractere:", nome[1:])
print("\nOs dois últimos caracteres:", nome[-2:])
print("\n")